## 一些数学技巧
依托 pytorch 工具库实现的数学定理的应用示范。

In [2]:
import torch

In [3]:
a = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float)
print(a.shape)
print(a)

torch.Size([3, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [5]:
print(torch.mean(a)) # 所有元素求平均
print(torch.mean(a, dim=0)) # 沿着 0 维（行）求平均，列维度保留。
print(torch.mean(a, dim=1)) # 沿着 1 维（列）求平均，行维度保留。
print(torch.mean(a, dim=0, keepdim=True))
print(torch.mean(a, dim=1, keepdim=True))

tensor(5.)
tensor([4., 5., 6.])
tensor([2., 5., 8.])
tensor([[4., 5., 6.]])
tensor([[2.],
        [5.],
        [8.]])


In [7]:
torch.manual_seed(42)
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=torch.float)
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b # 只有 a 的列与 b 的行一致，就可以进行矩阵乘法，结果的shape就是 a 的行 x b 的列。
print('a=')
print(a)
print('----------')
print('b=')
print(b)
print('----------')
print('a @ b=')
'''
1. 计算 c [0][0]（第一行第一列）
a 第一行：[1, 2, 3]
b 第一列：[2, 6, 6]
计算：1×2 + 2×6 + 3×6 = 2 + 12 + 18 = 32 → 对应结果 32.
2. 计算 c [0][1]（第一行第二列）
a 第一行：[1, 2, 3]
b 第二列：[7, 4, 5]
计算：1×7 + 2×4 + 3×5 = 7 + 8 + 15 = 30 → 对应结果 30.
3. 计算 c [1][0]（第二行第一列）
a 第二行：[4, 5, 6]
b 第一列：[2, 6, 6]
计算：4×2 + 5×6 + 6×6 = 8 + 30 + 36 = 74 → 对应结果 74.
4. 计算 c [1][1]（第二行第二列）
a 第二行：[4, 5, 6]
b 第二列：[7, 4, 5]
计算：4×7 + 5×4 + 6×5 = 28 + 20 + 30 = 78 → 对应结果 78.
5. 计算 c [2][0]（第三行第一列）
a 第三行：[7, 8, 9]
b 第一列：[2, 6, 6]
计算：7×2 + 8×6 + 9×6 = 14 + 48 + 54 = 116 → 对应结果 116.
6. 计算 c [2][1]（第三行第二列）
a 第三行：[7, 8, 9]
b 第二列：[7, 4, 5]
计算：7×7 + 8×4 + 9×5 = 49 + 32 + 45 = 126 → 对应结果 126.
'''
print(c)

a=
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
----------
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
----------
a @ b=
tensor([[ 32.,  30.],
        [ 74.,  78.],
        [116., 126.]])


In [9]:
torch.tril(torch.ones(3,3))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [11]:
a = torch.tensor([
    [1, 2],
    [4, 5],
    [7, 8]
], dtype=torch.float)
torch.sum(a, 0) # tensor([12., 15.])
torch.sum(a, 0, True) # tensor([[12., 15.]]) # 应用于 batchNorm 之中

torch.sum(a, 1) # tensor([ 3.,  9., 15.])
torch.sum(a, 1, True) # tensor([[ 3.], # 应用于 layerNorm 之中
                       #        [ 9.],
                       #        [15.]])

a / torch.sum(a, 0, True) # ❌ tensor([[0.0833, 0.1333],
                        #           [0.3333, 0.3333],
                        #           [0.5833, 0.5333]])

a / torch.sum(a, 1, True) # ✅ tensor([[0.3333, 0.6667], # 应用于 softmax 之中
                        #           [0.4444, 0.5556],
                        #           [0.4667, 0.5333]])

tensor([[0.3333, 0.6667],
        [0.4444, 0.5556],
        [0.4667, 0.5333]])

In [13]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b
print('a=')
print(a)
print('----------')
print('b=')
print(b)
print('----------')
print('a @ b=')
print(c)

a=
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
----------
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
----------
a @ b=
tensor([[ 2.,  7.],
        [ 8., 11.],
        [14., 16.]])


In [14]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a, 1, True)
b = torch.randint(0, 10, (3, 2)).float()
c = a @ b
print('a=')
print(a)
print('----------')
print('b=')
print(b)
print('----------')
print('a @ b=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
----------
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
----------
a @ b=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])
